### ISSUE TITLE
Redirecting & Notice / Flash / Notification

### ISSUE THREAD

**Issue by ihateonions-uk** [osiset/laravel-shopify#860]
HI, after updating to the latest version (17), I cannot work out how to get the notice / flash messages to show, and handle the redirect back to a route. It seems to update and the POST has worked, but the redirect wont.

My current setup had this within a controller which would trigger the toastr message.

`$notice = array(
            'message' => 'Email settings updated successfully',
            'alert-type' => 'success'
);

return Redirect::to('/email-builder')->with($notice);` 

I also changed the return to 'return redirect()->tokenRedirect('email-builder');' within my controller function but this causes an error. See the stack trace, https://flareapp.io/share/x5MqqXx5

I saw a post from squatto about this notice issue but still cannot get this to work but I believe its maybe not working for me due to the redirect back to route not working correctly. https://github.com/osiset/laravel-shopify/issues/744#issuecomment-837189540

Is there any advice / guidance someone could offer please, or an entry into the wiki maybe on how to handle a redirect to a route from a controller or web.php. I found one comment about tokenRedirect() but cannot find any further information on this.

Thanks in advanced

**Comment by osiset** [comment]
Notice will have to be flat I think, and not an array.

`return redirect()->tokenRedirect('email-builder', ['notice' => 'Email settings updated suucessfully']);`

I had luck with the above, but I did just push a commit to look for $flashNotice and $flashError as well.

**Comment by mattias** [comment]
When I try the above I get the following issue:
1. It ignores my `layouts/default.blade.php`, instead is uses `vendor/shopify-app/layouts/default.blade.php`.
2. When this happens, the files are identical, I get the following error: _Trying to get property 'name' of non-object_.
The error happens on this line: `apiKey: "{{ \Osiset\ShopifyApp\Util::getShopifyConfig('api_key', $shopDomain ?? Auth::user()->name ) }}",`

`$shopDomain` seems to exist but the user hasn't been automatically logged in? I only get this on a `tokenRedirect`, I can navigate around in the app otherwise.

How is Auth::user initiated on a request? I know I have to do it manually in certain cases. In this case it is a redirect from an update action, which was initiated with a POST request at first.

**Comment by mattias** [comment]
Ok, so. When `layouts/default.blade.php` is used I get the $shopDomain variable. But when `vendor/shopify-app/layouts/default.blade.php` is used, seems to be used when using tokenRedirect(), $shopDomain is empty and Auth::user() is empty.

Redirect::back()->with() works, just that the ->with() info does not tag along to the next page. If only I could add a GET variable with Redirect::back(). I already have the token solved with Inertia.js so I don't really need tokenRedirect(). Anyone has any ideas?

**Comment by osiset** [comment]
If you change Auth::user() to request()->user(), does it help?

**Comment by ihateonions-uk** [comment]
'Change Auth::user() to request()->user()', didn't help, the issue still exists for me unfortunately.

I also created 2 new servers and installed a new Laravel 8 on both, then installed this package on both and done a simple test on 1 of them, all worked fine with posting and redirecting with notice response. But moved my prebuilt controllers and views etc from my old project and its getting the same error again.

Something must be causing this in our code and not the package especially as Osiset isn't able to replicate this and no one else is reporting it. Im going to go through bit by bit on my new working server and and see if I can replicate the issue. Fingers crossed I can come back with a solution / cause of the issue for me.

**Comment by mattias** [comment]
I tried this redirect:
```php
        return Redirect::route('settings.edit',
            ['notice' => 'Settings updated.'],
            302,
            ['Authorization' => $request->header('authorization')]
        );
```
And I don't get the error any more for the user, and the page reloads and saves correctly.

Now I need to figure out how to actually catch the notice message in Inertia.js.

**Comment by osiset** [comment]
@ihateonions-uk What do you mean by moving it to your old project? Maybe theres a hint there.

**Comment by ihateonions-uk** [comment]
@osiset I moved my files from the old server with this missing name error, into the NEW server. These file were my controllers, and resources. That was it, i didn't move anything else over.

So the new server with a fresh install of this package, but with my existing controllers and resources from my old server that returns the error. Thats why I think something in my code must be causing this problem, as nothing was moved from old to new in regards to Laravel files or package files, only my custom controllers and resources.

Whereas the second new server I created which I didn't move any controllers or resources into, works fine with a test post route, controller and resource.

Does that make sense?

**Comment by osiset** [comment]
I am not sure what would cause that... maybe delete your vendors folder on your old project and reinstall with composer, maybe a dependency is different. In anycase, I will close this for now since it seems to be something with your specific old project, thanks for looking into it :)

**Comment by softopia-tech** [comment]
> HI, after updating to the latest version (17), I cannot work out how to get the notice / flash messages to show, and handle the redirect back to a route. It seems to update and the POST has worked, but the redirect wont.
> 
> My current setup had this within a controller which would trigger the toastr message.
> 
> `$notice = array( 'message' => 'Email settings updated successfully', 'alert-type' => 'success' );
> 
> return Redirect::to('/email-builder')->with($notice);`
> 
> I also changed the return to 'return redirect()->tokenRedirect('email-builder');' within my controller function but this causes an error. See the stack trace, https://flareapp.io/share/x5MqqXx5
> 
> I saw a post from squatto about this notice issue but still cannot get this to work but I believe its maybe not working for me due to the redirect back to route not working correctly. [#744 (comment)](https://github.com/osiset/laravel-shopify/issues/744#issuecomment-837189540)
> 
> Is there any advice / guidance someone could offer please, or an entry into the wiki maybe on how to handle a redirect to a route from a controller or web.php. I found one comment about tokenRedirect() but cannot find any further information on this.
> 
> Thanks in advanced

This error is coming when the route u are visiting is not inside `verify.shopify` middleware
